import { DownloadCloud, FolderOpen, Globe2, PlugZap, Save, ShieldCheck, Wifi } from 'lucide-react';
import type { ConnectionConfig } from '../types';
interface SettingsPageProps { platform:string; otaSupported:boolean; config:ConnectionConfig; busy:boolean; onChange:(config:ConnectionConfig)=>void; onSave:()=>void; onTest:()=>void; otaPassword:string; onOtaPasswordChange:(value:string)=>void; }
const validHost=(value:string)=>{const h=value.trim(); return h.length>0&&h.length<=253&&!h.includes('://')&&!h.includes('/')&&!/\s/.test(h);};
const validPort=(value:number)=>Number.isInteger(value)&&value>=1&&value<=65535;
const validPath=(value:string)=>value.trim().startsWith('/')&&!/\s/.test(value.trim());
const validKey=(value:string)=>{const k=value.trim(); return k.length>=24&&k.length<=64&&/^[\x21-\x7e]+$/.test(k);};
export function SettingsPage({platform,otaSupported,config,busy,onChange,onSave,onTest,otaPassword,onOtaPasswordChange}:SettingsPageProps){
 const set=<K extends keyof ConnectionConfig>(key:K,value:ConnectionConfig[K])=>onChange({...config,[key]:value});
 const isMac=platform==='macos'; const local=validHost(config.localArduinoIp)&&validPort(config.localArduinoPort); const remote=validHost(config.arduinoIp)&&validPort(config.arduinoPort); const localApiAllowed=!isMac||config.macosLocalApiEnabled; const otaHost=config.otaUseApiHost?(config.arduinoIp||config.localArduinoIp):config.otaAddress; const canSave=((local&&localApiAllowed)||remote)&&validPath(config.arduinoApiPath)&&validKey(config.arduinoApiKey)&&(!otaSupported||(validHost(otaHost)&&validPort(config.otaPort)&&config.otaTimeoutSeconds>=30&&config.otaTimeoutSeconds<=600&&(config.otaUploadMode!=='custom'||Boolean(config.otaToolPath.trim())))); const prefix=config.arduinoApiPath.trim().replace(/\/+$/,'');
 const localUrl=local?`${config.localProtocol}://${config.localArduinoIp}:${config.localArduinoPort}${prefix}/api/v1/status`:''; const remoteUrl=remote?`${config.protocol}://${config.arduinoIp}:${config.arduinoPort}${prefix}/api/v1/status`:'';
 return <div className="page settings-page">
  <section className="panel settings-panel"><div className="panel-title"><div><p className="eyebrow">DIRECT MODE PROFIL</p><h2>Kapcsolat és hitelesítés</h2></div><ShieldCheck/></div><div className="notice"><PlugZap size={18}/><p>{isMac?'macOS alatt a távoli HTTPS/DDNS az elsődleges API-kapcsolat. A helyi Arduino külön HTTP-protokollt használ.':'A távoli és helyi végpont protokollja külön állítható.'}</p></div><div className="settings-grid">
   <label>Profil neve<input value={config.profileName} onChange={e=>set('profileName',e.target.value)}/></label><label>Távoli protokoll<select value={config.protocol} onChange={e=>set('protocol',e.target.value as 'http'|'https')}><option value="https">HTTPS</option><option value="http">HTTP</option></select></label>
   <label>Távoli IP vagy DDNS<input value={config.arduinoIp} placeholder="beta-lexyguruhome.ddns.net" onChange={e=>set('arduinoIp',e.target.value)}/></label><label>Távoli API-port<input type="number" value={config.arduinoPort} onChange={e=>set('arduinoPort',Number(e.target.value))}/></label>
   <label>Helyi protokoll<select value={config.localProtocol} onChange={e=>set('localProtocol',e.target.value as 'http'|'https')}><option value="http">HTTP</option><option value="https">HTTPS</option></select></label><label>Helyi IP<input value={config.localArduinoIp} placeholder="10.0.0.117" onChange={e=>set('localArduinoIp',e.target.value)}/></label><label>Helyi API-port<input type="number" value={config.localArduinoPort} onChange={e=>set('localArduinoPort',Number(e.target.value))}/></label>
   <label className="settings-span">Privát API path<input value={config.arduinoApiPath} onChange={e=>set('arduinoApiPath',e.target.value)}/></label><label className="settings-span">X-Device-Key<input type="password" value={config.arduinoApiKey} onChange={e=>set('arduinoApiKey',e.target.value)}/></label></div>
   {isMac&&<label className="check-row"><input type="checkbox" checked={config.macosLocalApiEnabled} onChange={e=>set('macosLocalApiEnabled',e.target.checked)}/>Haladó: közvetlen helyi API engedélyezése macOS-en</label>}<label className="check-row"><input type="checkbox" checked={config.preferLocal} disabled={isMac} onChange={e=>set('preferLocal',e.target.checked)}/>{isMac?'macOS-en a távoli HTTPS/DDNS mindig elsődleges':'Helyi kapcsolat előnyben részesítése'}</label><div className="endpoint-preview"><Wifi size={17}/><span>{local&&localApiAllowed?localUrl:isMac&&!config.macosLocalApiEnabled?'macOS-en a helyi API ki van kapcsolva.':'Nincs érvényes helyi cél.'}</span></div><div className="endpoint-preview"><Globe2 size={17}/><span>{remote?remoteUrl:'Nincs érvényes távoli cél.'}</span></div>
  </section>
  <section className="panel settings-panel"><div className="panel-title"><div><p className="eyebrow">FIRMWARE ÉS OTA</p><h2>Helyi arduinoOTA konzol</h2></div><FolderOpen/></div><label className="check-row"><input type="checkbox" checked={config.otaUseApiHost} disabled={isMac} onChange={e=>set('otaUseApiHost',e.target.checked)}/>{isMac?'macOS-en az OTA külön helyi címet használ':'Az OTA az aktív API-címet használja'}</label><div className="settings-grid">
   {(!config.otaUseApiHost||isMac)&&<label>OTA IP vagy DDNS<input value={config.otaAddress} onChange={e=>set('otaAddress',e.target.value)}/></label>}<label>OTA-port<input type="number" value={config.otaPort} onChange={e=>set('otaPort',Number(e.target.value))}/></label>
   <label>Uploader mód<select value={config.otaUploadMode} onChange={e=>set('otaUploadMode',e.target.value as ConnectionConfig['otaUploadMode'])}><option value="auto">Automatikus</option><option value="system">Rendszer</option><option value="bundled">Csomagolt</option><option value="custom">Egyedi útvonal</option></select></label><label className="settings-span">arduinoOTA útvonal<input value={config.otaToolPath} placeholder="/usr/local/bin/arduinoOTA" onChange={e=>set('otaToolPath',e.target.value)}/></label>
   <label>Timeout (mp)<input type="number" min={30} max={600} value={config.otaTimeoutSeconds} onChange={e=>set('otaTimeoutSeconds',Number(e.target.value))}/></label><label>OTA-jelszó<input type="password" value={otaPassword} onChange={e=>onOtaPasswordChange(e.target.value)}/></label></div><div className="endpoint-preview"><DownloadCloud size={17}/><span>OTA cél: {otaHost||'nincs'}:{config.otaPort} • {config.otaTimeoutSeconds}s</span></div>
  </section>
  <section className="panel settings-panel"><div className="panel-title"><div><p className="eyebrow">FRISSÍTÉSEK</p><h2>Alkalmazás- és firmware-csatorna</h2></div><DownloadCloud/></div><div className="settings-grid"><label>Alkalmazásfrissítési csatorna<select value={config.updateChannel} onChange={e=>set('updateChannel',e.target.value as 'stable'|'beta')}><option value="stable">Stabil – main release</option><option value="beta">Béta – prerelease</option></select></label><label>Firmware-frissítési csatorna<select value={config.firmwareUpdateChannel} onChange={e=>set('firmwareUpdateChannel',e.target.value as 'stable'|'beta')}><option value="stable">Stabil firmware</option><option value="beta">Béta firmware</option></select></label></div><label className="check-row"><input type="checkbox" checked={config.autoCheckUpdates} onChange={e=>set('autoCheckUpdates',e.target.checked)}/>Automatikus frissítéskeresés</label><label className="check-row"><input type="checkbox" checked={config.firmwareUpdateChecks} onChange={e=>set('firmwareUpdateChecks',e.target.checked)}/>Firmware-frissítések keresése</label><label className="check-row"><input type="checkbox" checked={config.autoDownloadUpdates} onChange={e=>set('autoDownloadUpdates',e.target.checked)}/>Automatikus letöltés, kézi telepítési megerősítéssel</label></section>
  <div className="settings-actions"><button className="secondary-button" disabled={busy||!canSave} onClick={onTest}><PlugZap size={17}/>Kapcsolat tesztelése</button><button className="primary-button" disabled={busy||!canSave} onClick={onSave}><Save size={17}/>Profil mentése</button></div>
 </div>;
}
