#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

echo "[1/6] Verziók ellenőrzése"
python3 scripts/check-versions.py

echo
echo "[2/6] Node.js szintaktikai ellenőrzés"
npm run check --silent

echo
echo "[3/6] Bash scriptek szintaktikai ellenőrzése"
while IFS= read -r -d '' script; do
  bash -n "${script}"
done < <(find deploy scripts -type f -name '*.sh' -print0)

echo
echo "[4/6] Kötelező fájlok ellenőrzése"
required_files=(
  "VERSION"
  ".editorconfig"
  ".env.example"
  "package.json"
  "package-lock.json"
  "server2_final.js"
  "server2_legacy.js"
  "server/core/runtime-paths.js"
  "server/core/config.js"
  "server/core/logger.js"
  "server/core/runtime-context.js"
  "server/security/roles.js"
  "server/security/api-token-store.js"
  "server/security/security-error.js"
  "server/security/user-repository.js"
  "server/security/session-service.js"
  "server/events/topics.js"
  "server/events/event-bus.js"
  "server/socket/socket-bootstrap-registry.js"
  "server/socket/socket-gateway.js"
  "server/arduino/arduino-error.js"
  "server/arduino/arduino-client.js"
  "server/led/led-error.js"
  "server/led/led-validation.js"
  "server/led/led-service.js"
  "server/schedule/schedule-error.js"
  "server/schedule/schedule-validation.js"
  "server/schedule/schedule-codec.js"
  "server/schedule/schedule-service.js"
  "server/schedule/local-schedule-repository.js"
  "server/schedule/local-schedule-runner.js"
  "server/schedule/local-schedule-service.js"
  "server/firmware/firmware-error.js"
  "server/firmware/firmware-release-client.js"
  "server/firmware/ota-runner.js"
  "server/firmware/firmware-service.js"
  "server/express/express-bootstrap-registry.js"
  "server/health-bootstrap.js"
  "server/api/v2/http-error.js"
  "server/api/v2/http-response.js"
  "server/api/v2/auth.js"
  "server/api/v2/session-routes.js"
  "server/api/v2/event-routes.js"
  "server/api/v2/authorize.js"
  "server/api/v2/cors-security.js"
  "server/api/v2/readiness.js"
  "server/api/v2/arduino-error-mapper.js"
  "server/api/v2/error-handler.js"
  "server/api/v2/routes.js"
  "server/api/v2/led-routes.js"
  "server/api/v2/schedule-routes.js"
  "server/api/v2/local-schedule-routes.js"
  "server/api/v2/firmware-routes.js"
  "server/api/v2/api-v2-bootstrap.js"
  "scripts/test-core-modules.js"
  "scripts/test-arduino-client.js"
  "scripts/test-server-platform-modules.js"
  "scripts/test-led-service.js"
  "scripts/test-api-v2-led.js"
  "scripts/test-schedule-service.js"
  "scripts/test-api-v2-schedule.js"
  "scripts/test-api-token-store.js"
  "scripts/test-session-service.js"
  "scripts/test-event-bus.js"
  "scripts/test-socket-gateway.js"
  "scripts/test-service-events.js"
  "scripts/test-api-v2-session-events.js"
  "scripts/test-update-rollback.sh"
  "scripts/test-local-schedule-repository.js"
  "scripts/test-local-schedule-runner.js"
  "scripts/test-firmware-service.js"
  "scripts/test-api-v2-extended.js"
  "scripts/test-health-endpoints.js"
  "scripts/test-api-v2.js"
  "docs/api/API_V2_CONTRACT.md"
  "docs/v5/SERVER_MODULE_MAP.md"
  "docs/v5/V5_REARCHITECTURE_CHECKLIST.md"
  "docs/v5/PACKAGE_MANIFEST_SESSION_EVENTS_ROLLBACK.json"
  "desktop-tauri/package.json"
  "desktop-tauri/package-lock.json"
  "desktop-tauri/src-tauri/Cargo.toml"
  "desktop-tauri/src-tauri/tauri.conf.json"
  "fejlesztes_readme.md"
  "deploy/ensure-node-dependencies.sh"
  "deploy/update-rollback-lib.sh"
  "deploy/update.sh"
  "server/core/lifecycle-manager.js"
  "server/core/shutdown-coordinator.js"
  "server/events/event-store.js"
  "server/observability/metrics-registry.js"
  "server/observability/audit-log.js"
  "server/observability/diagnostics-service.js"
  "server/api/v2/openapi-service.js"
  "server/api/v2/openapi-routes.js"
  "server/api/v2/user-routes.js"
  "server/api/v2/observability-routes.js"
  "scripts/test-lifecycle-manager.js"
  "scripts/test-metrics-registry.js"
  "scripts/test-event-store.js"
  "scripts/test-audit-log.js"
  "scripts/test-user-administration.js"
  "scripts/test-session-csrf.js"
  "scripts/test-local-schedule-update.js"
  "scripts/test-openapi-document.js"
  "scripts/test-alpha2-release-gate.js"
  "docs/api/openapi-v2.json"
  "docs/v5/ALPHA2_RELEASE_GATE.md"
  "deploy/test-alpha2-candidate.sh"
  "scripts/check-versions.py"
  "docs/v5/PACKAGE_MANIFEST_ADMIN_OPENAPI_OBSERVABILITY.json"
  "server/http/http-server-registry.js"
  "server/legacy/legacy-signal-guard.js"
  "server/legacy/legacy-response.js"
  "server/legacy/legacy-auth-middleware.js"
  "server/legacy/legacy-auth-routes.js"
  "server/legacy/legacy-settings-routes.js"
  "server/legacy/legacy-arduino-routes.js"
  "server/legacy/legacy-local-schedule-routes.js"
  "server/legacy/legacy-firmware-routes.js"
  "server/legacy/legacy-event-bridge.js"
  "server/legacy/legacy-api-bootstrap.js"
  "server/legacy/legacy-cron-guard.js"
  "server/legacy/legacy-cutover-service.js"
  "server/legacy/legacy-schedule-file-routes.js"
  "server/arduino/arduino-status-monitor.js"
  "server/arduino/arduino-console-service.js"
  "server/files/file-service-error.js"
  "server/files/schedule-file-service.js"
  "server/web/static-web-installer.js"
  "server/api/v2/arduino-console-routes.js"
  "server/api/v2/schedule-file-routes.js"
  "server/api/v2/cutover-routes.js"
  "server/api/v2/web-routes.js"
  "scripts/test-legacy-cron-guard.js"
  "scripts/test-arduino-status-monitor.js"
  "scripts/test-arduino-console-service.js"
  "scripts/test-schedule-file-service.js"
  "scripts/test-cutover-service.js"
  "scripts/test-static-web-installer.js"
  "scripts/test-cutover-package-manifest.js"
  "docs/v5/ALPHA2_CUTOVER_RUNBOOK.md"
  "docs/v5/PACKAGE_MANIFEST_SCHEDULE_CONSOLE_CUTOVER.json"
  "server/core/runtime-settings-service.js"
  "server/observability/prometheus-exporter.js"
  "server/api/v2/prometheus-routes.js"
  "server/api/v2/settings-routes.js"
  "scripts/test-prometheus-exporter.js"
  "scripts/test-runtime-settings-service.js"
  "scripts/test-http-server-registry.js"
  "scripts/test-legacy-signal-guard.js"
  "scripts/test-legacy-event-bridge.js"
  "scripts/test-legacy-adapters.js"
  "scripts/test-legacy-auth-local.js"
  "scripts/test-legacy-package-manifest.js"
  "docs/v5/LEGACY_ADAPTER_MIGRATION.md"
  "docs/v5/PACKAGE_MANIFEST_LEGACY_ADAPTERS_PROMETHEUS_SHUTDOWN.json"
  "server/security/api-token-repository.js"
  "server/security/api-token-service.js"
  "server/api/v2/token-routes.js"
  "server/firmware/firmware-backup-store.js"
  "scripts/generate-openapi-typescript.js"
  "scripts/test-api-token-administration.js"
  "scripts/test-firmware-backup-rollback.js"
  "scripts/test-ota-cancellation.js"
  "scripts/test-openapi-typescript-generator.js"
  "scripts/test-alpha2-candidate-tooling.js"
  "scripts/test-alpha2-candidate-package-manifest.js"
  "desktop-tauri/src/api/generated/api-v2-types.ts"
  "desktop-tauri/src/api/generated/api-v2-operations.ts"
  "desktop-tauri/src/api/generated/api-v2-client.ts"
  "desktop-tauri/src/api/generated/index.ts"
  "deploy/test-alpha2-lxc.sh"
  "deploy/build-versioned-release.sh"
  "deploy/verify-versioned-release.sh"
  "docs/v5/ALPHA2_LXC_GATE_RUNBOOK.md"
  "docs/v5/ALPHA2_RELEASE_CANDIDATE.md"
  "docs/v5/TYPESCRIPT_API_CLIENT.md"
  "docs/v5/FIRMWARE_BACKUP_ROLLBACK.md"
  "docs/v5/PACKAGE_MANIFEST_ALPHA2_CANDIDATE.json"
  "server/system/system-error.js"
  "server/system/maintenance-mode-service.js"
  "server/system/config-preflight-service.js"
  "server/system/snapshot-service.js"
  "server/system/migration-service.js"
  "server/system/release-info-service.js"
  "server/api/v2/system-admin-routes.js"
  "scripts/test-maintenance-mode.js"
  "scripts/test-config-preflight.js"
  "scripts/test-system-snapshot.js"
  "scripts/test-migration-service.js"
  "scripts/test-release-info-service.js"
  "scripts/test-system-admin-routes.js"
  "deploy/system-preflight.sh"
  "deploy/staging-deploy.sh"
  "docs/v5/SYSTEM_OPERATIONS.md"
  "desktop-tauri/src/api/runtime/runtime-error.mjs"
  "desktop-tauri/src/api/runtime/credential-vault.mjs"
  "desktop-tauri/src/api/runtime/server-profile-store.mjs"
  "desktop-tauri/src/api/runtime/connectivity-store.mjs"
  "desktop-tauri/src/api/runtime/offline-read-cache.mjs"
  "desktop-tauri/src/api/runtime/auth-controller.mjs"
  "desktop-tauri/src/api/runtime/event-stream-client.mjs"
  "desktop-tauri/src/api/runtime/desktop-api-runtime.mjs"
  "desktop-tauri/src/api/runtime/domain/led-api.mjs"
  "desktop-tauri/src/api/runtime/domain/schedule-api.mjs"
  "desktop-tauri/src/api/runtime/domain/firmware-api.mjs"
  "desktop-tauri/src/api/runtime/domain/system-api.mjs"
  "desktop-tauri/src/api/runtime/index.mjs"
  "desktop-tauri/src/api/runtime/index.d.mts"
  "desktop-tauri/src/api/create-desktop-api.ts"
  "desktop-tauri/src/api/react/DesktopApiContext.tsx"
  "desktop-tauri/src/api/index.ts"
  "scripts/test-desktop-server-profile.js"
  "scripts/test-desktop-credential-vault.js"
  "scripts/test-desktop-connectivity.js"
  "scripts/test-desktop-auth-controller.js"
  "scripts/test-desktop-event-stream.js"
  "scripts/test-desktop-api-runtime.js"
  "scripts/test-desktop-domain-adapters.js"
  "scripts/test-desktop-runtime-package-manifest.js"
  "docs/v5/DESKTOP_API_V2_RUNTIME.md"
  "desktop-tauri/package.json"
  "docs/v5/PACKAGE_MANIFEST_DESKTOP_API_RUNTIME.json"
  "desktop-tauri/src/api/ui/api-payload.mjs"
  "desktop-tauri/src/api/ui/api-payload.d.mts"
  "desktop-tauri/src/services/v5SystemModels.mjs"
  "desktop-tauri/src/services/v5SystemModels.d.mts"
  "desktop-tauri/src/hooks/useV5System.ts"
  "desktop-tauri/src/components/v5/V5StatusBadge.tsx"
  "desktop-tauri/src/components/v5/V5ConnectionPanel.tsx"
  "desktop-tauri/src/components/v5/V5ReleasePanel.tsx"
  "desktop-tauri/src/components/v5/V5PreflightPanel.tsx"
  "desktop-tauri/src/components/v5/V5MaintenancePanel.tsx"
  "desktop-tauri/src/components/v5/V5SnapshotPanel.tsx"
  "desktop-tauri/src/components/v5/V5MigrationPanel.tsx"
  "desktop-tauri/src/pages/V5SystemPage.tsx"
  "desktop-tauri/src/api-v2.css"
  "scripts/test-desktop-api-payload.js"
  "scripts/test-desktop-v5-models.js"
  "scripts/test-desktop-system-domain.js"
  "scripts/test-desktop-v5-ui-contract.js"
  "scripts/test-desktop-v5-system-ui-manifest.js"
  "docs/v5/DESKTOP_V5_SYSTEM_UI.md"
  "docs/v5/PACKAGE_MANIFEST_DESKTOP_V5_SYSTEM_UI.json"
)
for file in "${required_files[@]}"; do
  [[ -f "${file}" ]] || {
    echo "HIBA: hiányzik: ${file}" >&2
    exit 1
  }
done

echo
echo "[5/6] Teljes modul- és endpointteszt"
npm test --silent

echo
echo "[6/6] Titkos fájlok ellenőrzése"
if git ls-files | grep -E '(^|/)(secrets\.h|\.env|connection\.json)$' >/dev/null; then
  echo "HIBA: titkos vagy helyi konfigurációs fájl van Git-követés alatt:" >&2
  git ls-files | grep -E '(^|/)(secrets\.h|\.env|connection\.json)$' >&2
  exit 1
fi

echo
echo "A repository alapellenőrzése sikeres."
