import {useCallback,useEffect,useMemo,useState} from 'react';
import {CalendarDays,Cpu,Gauge,Lightbulb,Logs,RefreshCw,Settings,Wifi,Zap} from 'lucide-react';
import {api,Status,Strip} from './api';
import './style.css';

type Page='dashboard'|'leds'|'schedules'|'logs'|'firmware'|'settings';
const nav:[Page,string,any][]=[['dashboard','Áttekintés',Gauge],['leds','LED vezérlés',Lightbulb],['schedules','Heti program',CalendarDays],['logs','Naplók',Logs],['firmware','Firmware',Cpu],['settings','Rendszer',Settings]];
function Card({title,children}:{title:string,children:React.ReactNode}){return <section className="card"><h3>{title}</h3>{children}</section>}
function Value({label,value}:{label:string,value:React.ReactNode}){return <div className="value"><span>{label}</span><strong>{value??'—'}</strong></div>}
function fmtUptime(v:any){const n=Number(v||0),d=Math.floor(n/86400),h=Math.floor(n%86400/3600),m=Math.floor(n%3600/60);return `${d}n ${h}ó ${m}p`}

export default function App(){
 const[page,setPage]=useState<Page>('dashboard'),[status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[logs,setLogs]=useState<any[]>([]),[schedules,setSchedules]=useState<any>(null),[scheduleStatus,setScheduleStatus]=useState<any>(null),[ota,setOta]=useState<any>(null),[catalog,setCatalog]=useState<any>(null);
 const refresh=useCallback(async()=>{try{setError('');const s=await api.status();setStatus({...s,connected:true})}catch(e){setError(String(e));setStatus(x=>x?{...x,connected:false}:null)}},[]);
 useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(),10000);return()=>clearInterval(t)},[refresh]);
 useEffect(()=>{if(page==='logs')void api.logs(0).then(r=>setLogs(Array.isArray(r?.logs)?r.logs:[])).catch(e=>setError(String(e)));if(page==='schedules')void Promise.all([api.schedules(),api.scheduleStatus()]).then(([a,b])=>{setSchedules(a);setScheduleStatus(b)}).catch(e=>setError(String(e)));if(page==='firmware')void Promise.all([api.otaStatus(),api.firmwareCatalog()]).then(([a,b])=>{setOta(a);setCatalog(b)}).catch(e=>setError(String(e)))},[page]);
 const strips=useMemo(()=>status?.strips||[],[status]);
 async function updateStrip(strip:Strip,patch:Partial<Strip>){setBusy(true);try{await api.setLed({...strip,...patch});await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandmark"><Zap size={24}/></div><div><b>Arduino LED</b><span>Controller V5</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={18}/>{label}</button>)}</nav><div className="sidefoot"><span className={status?.connected?'dot ok':'dot'}></span>{status?.connected?'Arduino online':'Kapcsolat nélkül'}</div></aside>
 <main><header><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p>Rust LXC • Debian 13 • Direct API v1</p></div><button className="refresh" onClick={()=>void refresh()} disabled={busy}><RefreshCw size={18}/>Frissítés</button></header>{error&&<div className="error">{error}</div>}
 {page==='dashboard'&&<><div className="hero"><div><span className="eyebrow">DEVICE STATUS</span><h2>{status?.deviceName||'Arduino LED Controller'}</h2><p>{status?.deviceId||'—'} • {status?.ipAddress||'—'}</p></div><div className={status?.connected?'pill online':'pill'}><Wifi size={18}/>{status?.connected?'ONLINE':'OFFLINE'}</div></div><div className="grid"><Card title="Firmware"><Value label="Firmware" value={status?.firmwareVersion}/><Value label="Direct API" value={status?.directApiVersion}/><Value label="Uptime" value={fmtUptime(status?.uptime)}/></Card><Card title="Idő és scheduler"><Value label="Időzóna" value={status?.timezoneId}/><Value label="NTP" value={status?.timesynced?'Szinkronizálva':'Nincs sync'}/><Value label="Scheduler" value={status?.scheduler}/></Card><Card title="Programok"><Value label="Schedule count" value={status?.scheduleCount}/><Value label="Revision" value={status?.scheduleRevision}/><Value label="RSSI" value={status?.rssi!=null?`${status.rssi} dBm`:'—'}/></Card></div></>}
 {page==='leds'&&<div className="ledgrid">{strips.map(strip=><Card key={strip.id} title={`LED ${strip.id}`}><div className="ledstate"><span className={strip.enabled?'lamp on':'lamp'}></span><b>{strip.enabled?'Bekapcsolva':'Kikapcsolva'}</b></div><label>Fényerő <strong>{strip.brightness}</strong></label><input type="range" min="0" max="255" value={strip.brightness} disabled={busy} onChange={e=>void updateStrip(strip,{brightness:Number(e.target.value)})}/><div className="buttons"><button onClick={()=>void updateStrip(strip,{enabled:true})} disabled={busy}>BE</button><button onClick={()=>void updateStrip(strip,{enabled:false})} disabled={busy}>KI</button></div><Value label="Effekt" value={strip.effect}/><Value label="Sebesség" value={strip.speed}/></Card>)}</div>}
 {page==='schedules'&&<div className="grid"><Card title="Schedule állapot"><Value label="Count" value={scheduleStatus?.scheduleCount??status?.scheduleCount}/><Value label="Revision" value={scheduleStatus?.scheduleRevision??status?.scheduleRevision}/><Value label="Checksum" value={scheduleStatus?.scheduleChecksum}/></Card><Card title="Arduino programlista"><pre>{JSON.stringify(schedules,null,2)}</pre></Card></div>}
 {page==='logs'&&<Card title="Arduino konzol"><div className="logbox">{logs.length?logs.map((l,i)=><div key={l.id??i}><span>#{l.id??i}</span>{l.message??l.text??JSON.stringify(l)}</div>):'Nincs naplóbejegyzés.'}</div></Card>}
 {page==='firmware'&&<div className="grid"><Card title="OTA állapot"><pre>{JSON.stringify(ota,null,2)}</pre></Card><Card title="Firmware katalógus"><pre>{JSON.stringify(catalog,null,2)}</pre></Card></div>}
 {page==='settings'&&<div className="grid"><Card title="LXC szerver"><Value label="Web/API" value={window.location.origin}/><Value label="Platform" value="Debian 13 / Rust Axum"/><Value label="API" value="/api/v1"/><Value label="WebSocket" value="/api/v1/events/ws"/></Card><Card title="Arduino"><Value label="Device" value={status?.deviceName}/><Value label="Arduino IP" value={status?.ipAddress}/><Value label="Firmware" value={status?.firmwareVersion}/><Value label="Direct API" value={status?.directApiVersion}/></Card></div>}
 </main></div>
}
